plugins = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/michaeltang/Documents/GitHub/Great-One-Grind-Counter-and-info-PROJECT"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/sw.js"

[headers.values]
Cache-Control = "no-cache"